// frontend-vue/src/App.vue
<script setup>
import { io } from "socket.io-client";
import { onBeforeMount, ref } from "vue";

const socket = io("http://localhost:3001");

const messages = ref([]);
const messageText = ref("");
const isJoined = ref(false);
const name = ref("");
const typingDisplay = ref("");

onBeforeMount(() => {
  socket.emit("findAllMessages", {}, (response) => {
    messages.value = response;
  });

  socket.on("message", (message) => {
    messages.value.push(message);
  });

  socket.on("typing", ({ name, isTyping }) => {
    if (isTyping) typingDisplay.value = `${name} is typing...`;
    else typingDisplay.value = "";
  });
});

const join = () => {
  socket.emit("join", { name: name.value }, () => {
    isJoined.value = true;
  });
};

const sendMessage = () => {
  socket.emit("createMessage", { text: messageText.value }, () => {
    messageText.value = "";
  });
};

const emitTyping = () => {
  let timeout;

  socket.emit("typing", { isTyping: true });
  timeout = setTimeout(() => {
    socket.emit("typing", { isTyping: false });
  }, 2000);
};
</script>

<template>
  <div>
    <div v-if="!isJoined">
      <form @submit.prevent="join">
        <label>What's your name?</label>
        <input v-model="name" />
        <button type="submit">Send</button>
      </form>
    </div>
    <div v-else>
      <div v-for="message in messages">
        [{{ message.name }}]: {{ message.text }}
      </div>
      <div v-if="typingDisplay">{{ typingDisplay }}</div>
      <hr />
      <div>
        <form @submit.prevent="sendMessage">
          <label>Message:</label>
          <input v-model="messageText" @input="emitTyping" />
          <button type="submit">Send</button>
        </form>
      </div>
    </div>
  </div>
</template>

<style scoped></style>

// frontend-react/src/App.jsx
import { io } from "socket.io-client";
import { useEffect, useState } from "react";
import "./App.css";

const socket = io("http://localhost:3001");

function App() {
  const [messages, setMessages] = useState([]);
  const [text, setText] = useState("");
  const [isJoined, setIsJoined] = useState(false);
  const [name, setName] = useState("");
  const [typingDisplay, setTypingDisplay] = useState("");

  useEffect(() => {
    socket.emit("findAllMessages", {}, (response) => {
      setMessages(response);
    });

    socket.on("message", (message) => {
      setMessages((prev) => [...prev, message]);
    });

    socket.on("typing", ({ name, isTyping }) => {
      if (isTyping) setTypingDisplay(`${name} is typing...`);
      else setTypingDisplay("");
    });

    return () => {
      socket.off("message");
      socket.off("typing");
    };
  }, []);

  const joinRoom = (e) => {
    e.preventDefault();

    socket.emit("join", { name }, () => {
      setIsJoined(true);
    });
  };

  const sendMessage = (e) => {
    e.preventDefault();

    socket.emit("createMessage", { text }, () => {
      setText("");
    });
  };

  const emitTyping = () => {
    socket.emit("typing", { isTyping: true });
    setTimeout(() => {
      socket.emit("typing", { isTyping: false });
    }, 2000);
  };

  return (
    <main>
      {!isJoined ? (
        <div>
          <form onSubmit={joinRoom}>
            <label>What's your name?</label>
            <input
              type="text"
              value={name}
              onChange={(e) => setName(e.target.value)}
            />
            <button type="submit">Send</button>
          </form>
        </div>
      ) : (
        <div>
          <div>
            {messages?.map((message, index) => {
              return (
                <span key={index}>
                  <p>
                    {message.name}: {message.text}
                  </p>
                </span>
              );
            })}
          </div>
          {typingDisplay && <div>{typingDisplay}</div>}
          <hr />
          <div>
            <form onSubmit={sendMessage}>
              <label>Message:</label>
              <input
                type="text"
                value={text}
                onChange={(e) => setText(e.target.value)}
                onInput={() => emitTyping()}
              />
              <button type="submit">Send</button>
            </form>
          </div>
        </div>
      )}
    </main>
  );
}

export default App;
